### ISSUE TITLE
https://github.com/apache/commons-compress picks up old version

### ISSUE THREAD

**Issue by garydgregory** [jirutka/maven-badges#14]
The badge for https://github.com/apache/commons-compress picks up an older version than the current version. This is due to an old version being in Maven Central that used a timestamp as the version. Yikes. 

It would be nice if the version could be set in the URL instead of "the biggest version number".

Or an option to say "the newest version by date" would help.

Thoughts?

**Comment by chabala** [comment]
I don't see any spurious old version present in Central: http://central.maven.org/maven2/org/apache/commons/commons-compress/

**Comment by lukaszlenart** [comment]
Please reopen this ticket here
https://github.com/softwaremill/maven-badges
