### ISSUE TITLE
Add support for other repositories

### ISSUE THREAD

**Issue by marccarre** [jirutka/maven-badges#15]
Ideally, the repository should be passed as a parameter to support any existing repository. 

Example:

    [![OSSRH](https://maven-badges.herokuapp.com/oss.sonatype.org/groupID/artifactID/badge.svg)](https://maven-badges.herokuapp.com/oss.sonatype.org/groupID/artifactID)

for libraries hosted in [OSSRH](https://oss.sonatype.org).

Potentially related work: badges/shields#783

**Comment by lukaszlenart** [comment]
Please reopen this ticket here
https://github.com/softwaremill/maven-badges
