### ISSUE TITLE
maven-badges app is down

### ISSUE THREAD

**Issue by lukaszlenart** [jirutka/maven-badges#17]
Can you take a look on this? It looks there is a problem with the app and all badges are missing :(

https://maven-badges.herokuapp.com/

**Comment by io7m** [comment]
```
$ curl -I 'https://maven-badges.herokuapp.com/maven-central/com.io7m.jcanephora/io7m-jcanephora'
HTTP/1.1 200 Connection established

HTTP/1.1 303 See Other
Date: Fri, 21 Apr 2017 19:27:55 GMT
Connection: keep-alive
Content-Type: text/html;charset=utf-8
Cache-Control: public, max-age=3600
Location: http://search.maven.org/#artifactdetails%7Ccom.io7m.jcanephora%7Cio7m-jcanephora%7C0.53.1%7C
Content-Length: 0
X-Xss-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
Server: thin
Via: 1.1 vegur
```

Guessing something has changed in Sonatype's APIs...

**Comment by io7m** [comment]
It seems to be working again today. Thanks to whoever fixed this!

**Comment by radarsh** [comment]
It's down again!

**Comment by mastercake10** [comment]
Down again.

**Comment by io7m** [comment]
It seems like it goes up and down more or less at random. I'm not sure if someone is fixing it behind the scenes each time...

**Comment by lukaszlenart** [comment]
If this is a free dyno it can be only active 18h per day. Maybe we could overtake it.

**Comment by OhadR** [comment]
it is down again...

**Comment by lukaszlenart** [comment]
See #22 it should be ok now
