### ISSUE TITLE
maven-badges is down

### ISSUE THREAD

**Issue by liaochong** [jirutka/maven-badges#20]
[![Maven Central](https://maven-badges.herokuapp.com/maven-central/com.github.liaochong/spring-boot-starter-converter/badge.svg)](https://maven-badges.herokuapp.com/maven-central/com.github.liaochong/spring-boot-starter-converter)

**Comment by ben-manes** [comment]
Dead again with 503.

**Comment by vvatanabe** [comment]
Dead again with 503.
https://maven-badges.herokuapp.com/maven-central/com.nulab-inc/zxcvbn

**Comment by cnsgithub** [comment]
![image](https://user-images.githubusercontent.com/13161711/37904333-c224d514-30fb-11e8-95ce-b6d17580ada5.png)

**Comment by raychenon** [comment]
https://maven-badges.herokuapp.com/maven-central/org.zalando/play-zhewbacca_2.12

Someone wants to pay the bill of Heroku so everyone can benefit from this  :)

**Comment by cnsgithub** [comment]
In the meanwhile I use https://shields.io as an alternative...

**Comment by brunchboy** [comment]
Does anyone know a way to have shields.io link to your latest artifact details page though? That was a very nice feature of maven-badges. 😞

**Comment by Ivan97** [comment]
@brunchboy I just deployed a service the same function as maven-badges.
check it out!
https://github.com/Ivan97/maven-badges-generator

**Comment by brunchboy** [comment]
Thanks, @Ivan97  that looks very promising! What are your costs, though? I’m torn between moving to your new service, which would let me automatically link to the right artifact page, and doing that manually with shields.io, which is not as likely to disappear the way this original service did.

**Comment by Ivan97** [comment]
@brunchboy It`s totally free,running on heroku 7*24.
Just like you,I thought this original service would never come back,so I stolen the idea,but as @jirutka said in issue #22 ,maybe the original service will soon come back,in one way or another.So,whether to use the original service or mine,suit yourself :)
By the way,thank you for all your work.@jirutka

**Comment by lukaszlenart** [comment]
See #22 it should be ok now

**Comment by brunchboy** [comment]
Thanks so much for all your help, everyone, and especially @Ivan97 for making sure I saw these solutions were being put together.
