### ISSUE TITLE
Please transfer service to SoftwareMill

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [jirutka/maven-badges#22]
@jirutka please transfer
down https://github.com/jirutka/maven-badges/issues/17
down https://github.com/jirutka/maven-badges/issues/20

@lukaszlenart please clone or deploy new serivce

**Comment by brunchboy** [comment]
It’s not as obsolete as you thought, as shields.io doesn’t let you link to the actual latest artifact information the way you did. Thanks for having this up for so long, in any case! 😄

**Comment by lukaszlenart** [comment]
@jirutka can you transfer the dyno to SoftwareMill at Heroku?  It supposed to be under `Settings` in the `Transfer Ownership` section. If not, please add me as a collaborator and I will transfer it. In such case we will be able to pay for the dyno.

The code can stay here at is.

**Comment by lukaszlenart** [comment]
Yes, the linking to the latest version is a killer feature, thanks for all your work!

**Comment by jirutka** [comment]
I’ve added you as a collaborator, then Heroku allowed me to transfer ownership to you. I’ve also added you as collaborator to this repository.

Thank you for taking care of this!

**Comment by lukaszlenart** [comment]
hm... I do not see the app in Heroku dashboard, what account did you use, `lukasz dot lenart at gmail dot com`?

**Comment by lukaszlenart** [comment]
I got it invitation but you must transfer the app to me, in other case I won't be able to transfer it back to SML

**Comment by jirutka** [comment]
> what account did you use, lukasz dot lenart at gmail dot com?

No, the only email address of yours I found is `lukasz at lenart dot org dor pl`.

> I got the invitation but you must transfer the app to me

I did that, it’s pending, i.e. waiting for your approval.

**Comment by lukaszlenart** [comment]
Ah, right. I did miss a bar with the Accept button. Now it should be ok, transferred under SML. Thanks a lot and keep up your superb work!

**Comment by OhadR** [comment]
Well done!!

**Comment by Andrei-Pozolotin** [comment]
thank you guys

**Comment by aleksandr-m** [comment]
@jirutka @lukaszlenart Can we have more colors now - #12 ? :smirk:
