### ISSUE TITLE
Image badge retrieval is failing

### ISSUE THREAD

**Issue by oscarlvp** [jirutka/maven-badges#23]
I set up the url to retrieve the badge for my artefact in Maven Central like this:
https://maven-badges.herokuapp.com/maven-central/eu.stamp-project/descartes/badge.svg?style=flat

If the request is made directly in the browser I get this answer:
`Something went wrong, please open an issue on https://github.com/jirutka/maven-badges/issues`
So, I'm opening the issue. :)
It works with `png` extension. 

On a regular README markdown document, the retrieval fails due to `Gateway Timeout` with both extensions.

**Comment by lukaszlenart** [comment]
Now it works, maybe you have hit the time when dynos were restarted at Heroku. It happens from time to time.

**Comment by felixbarny** [comment]
Does still not seem to work:

![screen shot 2018-04-11 at 10 39 31](https://user-images.githubusercontent.com/2163464/38605830-b7757904-3d74-11e8-8ba0-9a111aff5b49.png)

**Comment by lukaszlenart** [comment]
Hm... worked in the morning, checking logs

**Comment by jhalterman** [comment]
Just noticed the same thing with another project:

https://github.com/jhalterman/failsafe

**Comment by lukaszlenart** [comment]
This happen randomly but now it's ok
