### ISSUE TITLE
The badges stopped working as of today

### ISSUE THREAD

**Issue by Nadahar** [jirutka/maven-badges#26]
I don't know what's causing it, but they worked yesterday. To me it seems like https://maven-badges.herokuapp.com might have stopped serving badges.

Is the permanent? I'd like to know if I need to find another solution. This one has been great this far.

**Comment by lukaszlenart** [comment]
It's rather temporary as this works on Heroku and they can temporally shutdown a service which cause a huge traffic ;-)

**Comment by Nadahar** [comment]
Do you know that they will open it again? The text when you enter [maven-badges.herokuapp.com]( https://maven-badges.herokuapp.com) is: 
> Nothing is here, see https://github.com/jirutka/maven-badges.

It seems a bit strange to me if they bothered to put that text there if the shutdown was temporary - or am I missing something?

**Comment by lukaszlenart** [comment]
Yeah, I see this but I have no clue why it happens, maybe it is related to shields.io as well - now it works :)

**Comment by Nadahar** [comment]
Ok, great :wink:

**Comment by lukaszlenart** [comment]
And done, migrated to nodejs
https://github.com/softwaremill/maven-badges

**Comment by lukaszlenart** [comment]
hm... you know, code should be self-explanatory ;-) Feel free to register an issue for that, then we won't forget it :)
