### ISSUE TITLE
Maven Badges doesn't work anymore

### ISSUE THREAD

**Issue by lopspower** [jirutka/maven-badges#5]
I call that : 
https://maven-badges.herokuapp.com/maven-central/com.mikhaellopez/circularimageview/badge.svg

I my result is : 
Something went wrong, please open an issue on https://github.com/jirutka/maven-badges/issues

**Comment by fabienrenaud** [comment]
+1, same issue on my github page and many others, including this project's github page.

**Comment by lopspower** [comment]
@fabienrenaud I recommend you this alternative that still allows more things: http://shields.io/

**Comment by verhagen** [comment]
+1, all badges no longer seem, to work...

**Comment by ducin** [comment]
Many badges in swagger.io's readme files are down as well...

**Comment by jirutka** [comment]
Sorry for inconveniences, it was problem on Heroku. I’ve upgraded to the latest Heroku’s [cedar stack](https://devcenter.heroku.com/articles/cedar-14-migration) and the problem disappeared.

**Comment by fehguy** [comment]
thank you @jirutka

**Comment by melezov** [comment]
Thanks!

**Comment by verhagen** [comment]
Cool THX!
