### ISSUE TITLE
Support for version ranges?

### ISSUE THREAD

**Issue by PascalSchumacher** [jirutka/maven-badges#7]
Hi,

thanks for supplying this great badge. :+1: 

Is it possible to specify a version range of an artifact, e.g show latest 1.x version?

Thanks,
Pascal

**Comment by klopfdreh** [comment]
+1

**Comment by chrisalice** [comment]
Also would be great to be able to exclude "unstable" artifacts like 1.2-alpha.1 (anything with alphabetic characters, essentially)

**Comment by lukaszlenart** [comment]
Please reopen this ticket here
https://github.com/softwaremill/maven-badges
