### ISSUE TITLE
Link crashes

### ISSUE THREAD

**Issue by pathikrit** [jirutka/maven-badges#8]
See: <https://maven-badges.herokuapp.com/maven-central/com.github.pathikrit/better-files_2.11/badge.svg?style=flat>

Obviously, it is on Maven Central:  <http://search.maven.org/#artifactdetails%7Ccom.github.pathikrit%7Cbetter-files_2.11%7C2.14.0%7Cjar>

**Comment by jirutka** [comment]
This service uses shields.io to generate a badge image and they have an outage.

**Comment by pathikrit** [comment]
I don't that's the cause since this works just fine: https://maven-badges.herokuapp.com/maven-central/cz.jirutka.rsql/rsql-parser/badge.svg (I thought it was caching issue but I did a hard refresh).

**Comment by jirutka** [comment]
I'm quite sure about it, look at https://img.shields.io/.
